### ISSUE TITLE
Feature Request: support for app-only OAuth with bearer tokens (Premium API)

### ISSUE THREAD

**Issue by lcichanowicz** [twitter/twurl#82] opened 2018-02-08 16:35 UTC
It would be great if twurl supported app-only OAuth with bearer tokens for use with the Premium APIs (30day and fullarchive).

**Comment by andypiper** [comment] 2018-02-08 18:14
This is actually a duplicate of #47 - but thanks for raising it again. Will see what we can do. I'm going to close this one out to focus on the other issue as the core ask.

**Closed by andypiper** 2018-02-08 18:14 UTC
Labels: Enhancement
